# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-19 13:36
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django_extensions.db.fields
import enumfields.fields
import torrents.enums


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Torrent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=150)),
                ('hash', models.CharField(db_index=True, max_length=40, unique=True)),
                ('progress', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('size', models.PositiveIntegerField(default=0)),
                ('finished', models.BooleanField(default=False)),
                ('private', models.BooleanField(default=False)),
                ('files', models.ManyToManyField(to='files.File')),
                ('status', enumfields.fields.EnumField(default='in queue', enum=torrents.enums.Status, max_length=20)),
                ('ratio', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3)),
            ],
            options={
                'ordering': ('-id',),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='torrent',
            options={'ordering': ('-id',)},
        ),
    ]
