# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-19 13:24
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields
import enumfields.fields
import files.enums


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('volume', enumfields.fields.EnumField(enum=files.enums.Volume, max_length=20)),
                ('path', models.FilePathField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('ext', models.CharField(max_length=5)),
                ('size', models.PositiveIntegerField(default=0)),
                ('content_type', models.CharField(max_length=20, null=True)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ('-id',)},
        ),
    ]
